spring:
  shell:
    interactive:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate